---

language: ruby
sudo: required
env:
  global:
    - CI_HOME=`pwd`
services:
  - docker
before_install:
  - echo $CI_HOME
  - docker pull franklinkim/ansible-trusty
#install:
#  - ansible-galaxy install franklinkim.openssl
#  - ansible-galaxy install franklinkim.htpasswd
#
#
script:
  - docker run -d --name ansible -v $CI_HOME:/opt/ansible franklinkim/ansible-trusty /bin/sh -c "ansible-playbook -i 'localhost,' -c local /opt/ansible/test.yml"
  - docker ps -a
  #- docker exec -u root ansible sh -c "ls -la /opt/ansible"
