---

language: ruby
sudo: required
env:
  global:
    - CI_HOME=`pwd`
    - ROLE_NAME=franklinkim.apache2
services:
  - docker
before_install:
  - docker pull franklinkim/ansible-trusty
#install:
#  - ansible-galaxy install franklinkim.openssl
#  - ansible-galaxy install franklinkim.htpasswd
#
#
script:
  - docker run -v $CI_HOME:/opt/ansible franklinkim/ansible-trusty test/run.sh
