---

language: ruby
sudo: required
env:
  global:
    - CI_HOME=`pwd`
services:
  - docker
before_install:
  - echo $CI_HOME
  - docker pull franklinkim/ansible-trusty
#install:
#  - ansible-galaxy install franklinkim.openssl
#  - ansible-galaxy install franklinkim.htpasswd
#
#
script:
  - docker run -v $(pwd)/test:/opt/ansible -v $(pwd):/etc/ansible/roles/franklinkim.apache2 franklinkim/ansible-trusty ./run.sh
