---

language: ruby
sudo: required
services:
  - docker
before_install:
  - docker pull franklinkim/ansible-trusty
#install:
#  - ansible-galaxy install franklinkim.openssl
#  - ansible-galaxy install franklinkim.htpasswd
#
#
script:
  - docker run -d -v $(pwd):/opt/ansible franklinkim/ansible-trusty test/run.sh
