---

language: ruby
sudo: required
services:
  - docker
install:
  - docker pull franklinkim/ansible:ubuntu-trusty
script:
  - docker run -v $(pwd):/opt/ansible franklinkim/ubuntu-trusty tests/run.sh
