---

language: ruby
sudo: required
env:
  global:
    - CI_HOME=`pwd`
services:
  - docker
before_install:
  - echo $CI_HOME
  - docker pull franklinkim/ansible-trusty
#install:
#  - ansible-galaxy install franklinkim.openssl
#  - ansible-galaxy install franklinkim.htpasswd
#
#
script:
  - docker run -v $CI_HOME:/opt/ansible franklinkim/ansible-trusty ansible-playbook -i "localhost," -c local test.yml
