---

language: ruby
sudo: required
env:
  global:
    - CI_HOME=`pwd`
services:
  - docker
before_install:
  - echo $CI_HOME
  - docker pull franklinkim/ansible-trusty
#install:
#  - ansible-galaxy install franklinkim.openssl
#  - ansible-galaxy install franklinkim.htpasswd
#
#
script:
  - docker run -v $(pwd):/opt/ansible franklinkim/ansible-trusty ansible all -i 'localhost,' -c local -m shell -a 'echo hello world'
  - docker run -v $(pwd):/opt/ansible franklinkim/ansible-trusty ansible all -i 'localhost,' -c local -m shell -a 'pwd'
  - docker run -v $(pwd):/opt/ansible franklinkim/ansible-trusty ansible all -i 'localhost,' -c local -m shell -a 'ls -la'
  - docker run -v $(pwd):/opt/ansible franklinkim/ansible-trusty ansible-playbook -i 'localhost,' -c local test.yml
