---

language: ruby
sudo: required
env:
  global:
    - CI_HOME=`pwd`
services:
  - docker
before_install:
  - echo $CI_HOME
  - docker pull franklinkim/ansible-trusty
  - docker run -d --name ansible -v $CI_HOME:/opt/ansible franklinkim/ansible-trusty /bin/sh -c "while true; do ping 8.8.8.8; sleep 1; done"
  - docker ps -a
#install:
#  - ansible-galaxy install franklinkim.openssl
#  - ansible-galaxy install franklinkim.htpasswd
#
#
script:
  - docker exec -it ansible /bin/sh -c "ls -la /opt/ansible"
