---

- include: install.yml
- include: configure.yml
- include: rules.yml
- include: remove_default.yml
- include: manage_confs.yml
- include: manage_sites.yml
- include: manage_modules.yml
- include: service.yml
